services:
  - type: web
    name: my-portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.15.0
